In [ ]:
import numpy as np

In [ ]:
import torch

In [ ]:
from torch.utils.data import Dataset, TensorDataset

In [ ]:
X = torch.rand(100, 5)
y = 1*(torch.rand(100) < 0.5)

In [ ]:
X, y

(tensor([[9.4156e-01, 1.6448e-02, 3.9043e-01, 5.7215e-01, 5.1806e-01],
         [3.4393e-01, 6.6998e-01, 6.1570e-01, 3.7246e-01, 7.4966e-01],
         [1.6649e-01, 9.4030e-01, 9.4931e-01, 2.1944e-01, 7.0778e-01],
         [7.5735e-01, 6.0426e-01, 7.1985e-02, 7.9662e-01, 9.5838e-04],
         [7.7182e-01, 6.5610e-01, 2.4376e-01, 3.1192e-01, 3.5930e-01],
         [9.1849e-01, 3.2103e-01, 1.1806e-02, 7.1624e-01, 2.7338e-01],
         [8.8812e-01, 4.8293e-01, 4.4150e-01, 5.8996e-01, 9.4374e-01],
         [7.7870e-01, 9.9432e-02, 5.3672e-01, 1.9485e-01, 8.9593e-01],
         [2.1126e-01, 9.9961e-01, 1.3965e-01, 9.4209e-01, 6.2643e-01],
         [5.6533e-03, 1.5835e-01, 1.1091e-01, 1.8224e-01, 7.5734e-01],
         [8.7559e-01, 6.9196e-01, 1.9312e-01, 1.1685e-01, 4.3639e-01],
         [5.6740e-01, 1.6512e-01, 4.9975e-01, 9.5604e-01, 6.9722e-01],
         [3.0811e-02, 1.0010e-01, 5.4849e-01, 5.2294e-01, 9.6587e-01],
         [6.9314e-01, 1.7143e-01, 7.2581e-01, 1.7944e-01, 3.3972e-01],
      

In [ ]:
ds = TensorDataset(X, y)

In [ ]:
print(ds[3])
print(X[3], y[3])

(tensor([0.7574, 0.6043, 0.0720, 0.7966, 0.0010]), tensor(0))
tensor([0.7574, 0.6043, 0.0720, 0.7966, 0.0010]) tensor(0)


In [ ]:
# create your own dataset class
class myDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
        self.n = X.shape[0]
    def __len__(self):
        return self.n
    def __getitem__(self, i):
        return (i, {"X":self.X[i], "y":self.y[i]})

In [ ]:
ds2 = myDataset(X, y)
ds2[4]

(4, {'X': tensor([0.7718, 0.6561, 0.2438, 0.3119, 0.3593]), 'y': tensor(1)})

## DataLoader

In [ ]:
from torch.utils.data import DataLoader

In [ ]:
dl = DataLoader(ds, batch_size=10)
it = iter(dl)
print(next(it))
print(next(it))

[tensor([[9.4156e-01, 1.6448e-02, 3.9043e-01, 5.7215e-01, 5.1806e-01],
        [3.4393e-01, 6.6998e-01, 6.1570e-01, 3.7246e-01, 7.4966e-01],
        [1.6649e-01, 9.4030e-01, 9.4931e-01, 2.1944e-01, 7.0778e-01],
        [7.5735e-01, 6.0426e-01, 7.1985e-02, 7.9662e-01, 9.5838e-04],
        [7.7182e-01, 6.5610e-01, 2.4376e-01, 3.1192e-01, 3.5930e-01],
        [9.1849e-01, 3.2103e-01, 1.1806e-02, 7.1624e-01, 2.7338e-01],
        [8.8812e-01, 4.8293e-01, 4.4150e-01, 5.8996e-01, 9.4374e-01],
        [7.7870e-01, 9.9432e-02, 5.3672e-01, 1.9485e-01, 8.9593e-01],
        [2.1126e-01, 9.9961e-01, 1.3965e-01, 9.4209e-01, 6.2643e-01],
        [5.6533e-03, 1.5835e-01, 1.1091e-01, 1.8224e-01, 7.5734e-01]]), tensor([1, 0, 1, 0, 1, 1, 1, 1, 1, 0])]
[tensor([[0.8756, 0.6920, 0.1931, 0.1168, 0.4364],
        [0.5674, 0.1651, 0.4998, 0.9560, 0.6972],
        [0.0308, 0.1001, 0.5485, 0.5229, 0.9659],
        [0.6931, 0.1714, 0.7258, 0.1794, 0.3397],
        [0.1614, 0.9243, 0.0636, 0.1777, 0.7712],
      

### Complex record structure

In [ ]:
dl2 = DataLoader(ds2, batch_size=10)
it = iter(dl2)
print(next(it))
print(next(it))

[tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), {'X': tensor([[9.4156e-01, 1.6448e-02, 3.9043e-01, 5.7215e-01, 5.1806e-01],
        [3.4393e-01, 6.6998e-01, 6.1570e-01, 3.7246e-01, 7.4966e-01],
        [1.6649e-01, 9.4030e-01, 9.4931e-01, 2.1944e-01, 7.0778e-01],
        [7.5735e-01, 6.0426e-01, 7.1985e-02, 7.9662e-01, 9.5838e-04],
        [7.7182e-01, 6.5610e-01, 2.4376e-01, 3.1192e-01, 3.5930e-01],
        [9.1849e-01, 3.2103e-01, 1.1806e-02, 7.1624e-01, 2.7338e-01],
        [8.8812e-01, 4.8293e-01, 4.4150e-01, 5.8996e-01, 9.4374e-01],
        [7.7870e-01, 9.9432e-02, 5.3672e-01, 1.9485e-01, 8.9593e-01],
        [2.1126e-01, 9.9961e-01, 1.3965e-01, 9.4209e-01, 6.2643e-01],
        [5.6533e-03, 1.5835e-01, 1.1091e-01, 1.8224e-01, 7.5734e-01]]), 'y': tensor([1, 0, 1, 0, 1, 1, 1, 1, 1, 0])}]
[tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), {'X': tensor([[0.8756, 0.6920, 0.1931, 0.1168, 0.4364],
        [0.5674, 0.1651, 0.4998, 0.9560, 0.6972],
        [0.0308, 0.1001, 0.5485, 0.5229, 0.9659]

In [ ]:
dl2 = DataLoader(ds2, batch_size=10, shuffle=True)
it = iter(dl2)
print(next(it))
print(next(it))

[tensor([45,  9, 15, 93, 99, 10, 95, 31,  5, 84]), {'X': tensor([[0.5845, 0.8004, 0.0333, 0.6976, 0.9794],
        [0.0057, 0.1583, 0.1109, 0.1822, 0.7573],
        [0.6750, 0.7081, 0.8473, 0.0167, 0.0087],
        [0.8286, 0.7859, 0.1141, 0.7789, 0.2866],
        [0.2473, 0.0829, 0.7298, 0.3762, 0.6593],
        [0.8756, 0.6920, 0.1931, 0.1168, 0.4364],
        [0.2649, 0.1222, 0.2253, 0.2142, 0.8417],
        [0.3618, 0.4810, 0.9360, 0.9926, 0.7071],
        [0.9185, 0.3210, 0.0118, 0.7162, 0.2734],
        [0.3949, 0.2429, 0.5108, 0.8177, 0.1964]]), 'y': tensor([0, 0, 0, 0, 1, 1, 1, 0, 1, 0])}]
[tensor([21, 25, 53, 52, 72, 58, 50, 36, 83, 13]), {'X': tensor([[0.9608, 0.1742, 0.2494, 0.3230, 0.4733],
        [0.0997, 0.3298, 0.9262, 0.0718, 0.3667],
        [0.5743, 0.4695, 0.7900, 0.9405, 0.6089],
        [0.1896, 0.5348, 0.6738, 0.4078, 0.8760],
        [0.8018, 0.0065, 0.0859, 0.8319, 0.0211],
        [0.9788, 0.0073, 0.3643, 0.3743, 0.9475],
        [0.7964, 0.1575, 0.6354, 0.463

## Iterable dataset

In [ ]:
# simple artificial iterable dataset
class myIterableDataset(IterableDataset):
    def __init__(self, n, transform=None, target_transform=None):
        self.transform = transform
        self.target_transform = target_transform
        self.n = n
    def __iter__(self):
        for x in range(self.n):
            yield {"x": torch.tensor(x), "x**2":torch.tensor(x**2)}

In [ ]:
di = myIterableDataset(100)
it = iter(di)
print(next(it))
print(next(it))

{'x': tensor(0), 'x**2': tensor(0)}
{'x': tensor(1), 'x**2': tensor(1)}


In [ ]:
dli = DataLoader(di, batch_size=10)
it = iter(dli)
print(next(it))
print(next(it))

{'x': tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'x**2': tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])}
{'x': tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), 'x**2': tensor([100, 121, 144, 169, 196, 225, 256, 289, 324, 361])}
